const service = require('./src/plug-services')
const store = require('./src/store-services')
const cost = require('./src/cost-services')
const params = require('./params.json')

// cost.dailyCost(params.cost)
// service.plugInfo(params.plug)
service.plugEmeter(params.plug)
service.plugUsage(params.plug)
store.levelStore(params.store)